"""
Django settings for med_box project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import (
    Path,
)
from med_box import (
    PROJECT_BASE_DIR,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = PROJECT_BASE_DIR


from pymodm.connection import (
    connect,
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "medical_store.apps.MedicalStoreConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "med_box.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "med_box.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASE_SETTINGS = {
    "mongodb": {
        "USER": os.environ.get("MONGO_USER"),
        "PASS": os.environ.get("MONGO_PASSWORD"),
        "DB_NAME": os.environ.get("MONGO_DB_NAME"),
        "CLUSTER_NAME": os.environ.get("MONGO_CLUSTER_NAME"),
    }
}

# connect(
#     f'mongodb+srv://{DATABASE_SETTINGS["mongodb"].get("USER")}:{DATABASE_SETTINGS["mongodb"].get("PASS")}@{DATABASE_SETTINGS["mongodb"].get("CLUSTER_NAME")}.qdbg2.mongodb.net/{DATABASE_SETTINGS["mongodb"].get("DB_NAME")}?retryWrites=true&w=majority'
# )
connect(
    "mongodb+srv://phoenix_124:2JBlfpWLZKgZz9CJ@shop.kxdzn.mongodb.net/medbox?retryWrites=true&w=majority"
)

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# EMAIL SENDING

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get("SMTP_HOST")
EMAIL_HOST_PASSWORD = os.environ.get("SMTP_HOST_PASSWORD")
